# Site wide configuration

title:            Pixelized Thoughts
locale:           en_US
url:              http://hendrasaputra.com


# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Hendra Saputra
  avatar: hs-photo.jpg
  bio: "Insatiable knowledge seeker, code monkey, movie addict."
  email: me@hendrasaputra.com
  disqus-shortname:
  twitter: hendrasaputra
  facebook: abinyamirza
  google:
    plus: HendrasaputraWalad
    analytics: UA-1749517-5
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: hendrasaputra
  stackoverflow: 76045/hendrasaputra #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: hendrasaputra
  xing: #username
  instagram: hendrasaputra
  lastfm: #username
  tumblr: hendrasaputra
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: hendrasaputra
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

theme: jekyll-theme-minimal