# Site
name: 'Pixelized Thoughts'
description: 'Hensap Thoughts and Musings'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
apple-touch-icon: 'assets/images/apple-touch-icon.png'
favicon-32x32: 'assets/images/favicon-32x32.png'
favicon-16x16: 'assets/images/favicon-16x16.png'
baseurl: ''
disqus: 'hendrasaputra'
email: 'hendrasaputra@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hendrasaputra:
      name:           Hendra Saputra
      site:           http://www.hendrasaputra.com
      avatar:         assets/images/hs-avatar.jpg
      bio:            "Lifelong Learner. Tech Observer. Casual Photographer. Avid Reader."
      email:          hendrasaputra@gmail.com
      twitter:        https://twitter.com/hendrasaputra
       
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hendrasaputra
      avatar: assets/images/hs-avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]